# Generated by Django 3.0.1 on 2019-12-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.ImageField(default=0, upload_to='', verbose_name=20),
            preserve_default=False,
        ),
    ]
